/**
 * The content contract for this portfolio.
 *
 * This file is the single source of truth. It is used by:
 *   - the site, to load and type content          (src/lib/content.ts)
 *   - `npm run validate`, to check every project  (scripts/validate-content.ts)
 *   - `npm run new:project`, to scaffold one      (scripts/new-project.mjs)
 *
 * If you are an agent adding a project, you do not need to read this file —
 * read AGENTS.md, then run `npm run validate` and fix what it tells you.
 */
import { z } from "zod";

/** Media paths are relative to the project's own folder, e.g. "media/cover.webp". */
const MediaPath = z
  .string()
  .regex(
    /^media\/[A-Za-z0-9._-]+\.(webp|jpg|jpeg|png|mp4|webm)$/,
    'must look like "media/name.webp" — relative to the project folder, no subfolders',
  );

export const MediaSchema = z.object({
  src: MediaPath,
  kind: z.enum(["image", "video"]),
  /** Poster frame for videos. Generated by `npm run media`. */
  poster: MediaPath.nullable().default(null),
  /** Required on images for accessibility. Describe what is shown, not "screenshot of app". */
  alt: z.string().min(1).nullable().default(null),
  caption: z.string().nullable().default(null),
});

export const SectionSchema = z.object({
  heading: z.string().min(1).nullable().default(null),
  /** One string per paragraph. Plain text — no HTML, no markdown. */
  body: z.array(z.string().min(1)).default([]),
  /** Optional fixed-width blocks for output, code, and alignment-sensitive text. */
  codeBlocks: z.array(z.string().min(1)).default([]),
  /** Desktop relationship between a section's prose and its single media item. */
  layout: z.enum(["stack", "media-left", "media-right"]).default("stack"),
  media: z.array(MediaSchema).default([]),
});

export const LinkSchema = z.object({
  label: z.string().min(1),
  href: z.string().url(),
});

export const ProjectSchema = z.object({
  /** Must equal the folder name. Lowercase kebab-case. */
  slug: z.string().regex(/^[a-z0-9]+(-[a-z0-9]+)*$/, "lowercase-kebab-case only"),
  title: z.string().min(1),
  /** One line, shown on the card. Keep under ~90 characters. */
  tagline: z.string().min(1).max(140),
  /** Two to four sentences. Shown at the top of the detail page. */
  summary: z.string().min(1),

  /** false hides the project from the site entirely, without deleting it. */
  published: z.boolean().default(false),
  /** Promotes the project to the top of the work page and onto the homepage. */
  featured: z.boolean().default(false),

  /** "YYYY" or "YYYY-MM". Drives ordering — newest first. null sorts last. */
  date: z
    .string()
    .regex(/^\d{4}(-\d{2})?$/, 'use "YYYY" or "YYYY-MM"')
    .nullable()
    .default(null),
  status: z.string().nullable().default(null),

  /**
   * What it is actually built with. Not file formats it happens to read.
   * Each entry renders as a pill, so it is a label, not a sentence — put the
   * explanation in a section instead.
   */
  tech: z.array(z.string().min(1).max(40, "a tech entry is a pill label, not a sentence")).default([]),
  links: z.array(LinkSchema).default([]),

  hero: MediaSchema.nullable().default(null),
  sections: z.array(SectionSchema).default([]),

  /** Internal. Never rendered. Use it to leave notes for yourself or the next agent. */
  notes: z.string().nullable().default(null),
});

export const ProfileSchema = z.object({
  name: z.string().min(1),
  headline: z.string().min(1),
  bio: z.string().min(1),
  location: z.string().nullable().default(null),
  email: z.string().email().nullable().default(null),
  resume: z.string().nullable().default(null),
  links: z.array(LinkSchema).default([]),
  /** Long-form "about" copy. One string per paragraph. */
  about: z.array(z.string().min(1)).default([]),
});

export type Media = z.infer<typeof MediaSchema>;
export type Section = z.infer<typeof SectionSchema>;
export type Link = z.infer<typeof LinkSchema>;
export type Project = z.infer<typeof ProjectSchema>;
export type Profile = z.infer<typeof ProfileSchema>;

/** Intrinsic image dimensions are read from the media file during content loading. */
export type ResolvedMedia = Media & {
  width?: number;
  height?: number;
};

export type ResolvedSection = Omit<Section, "media"> & {
  media: ResolvedMedia[];
};

/** A project with its media paths rewritten to public URLs (`/media/<slug>/...`). */
export type ResolvedProject = Omit<Project, "hero" | "sections"> & {
  hero: ResolvedMedia | null;
  sections: ResolvedSection[];
};
